#!/usr/bin/bash
#transfering file from client to server

#variables
path="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"
filename=$(basename "$BASH_SOURCE")
brown='\e[0;33m'
reset='\033[0m'
file="$1"
ip="$2"
user="ubuntu"
key="~/.ssh/id_rsa"

if [ $# -lt 4 ]
then
	  echo -e "${brown}Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY${reset}"
  else
	    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
